#%RAML 1.0 NamedExample
value:
  - 
    playerId: 1
    playerName: "Kuldeep"
    playerCountry: "India"
    playerClub: "Mavericks"
  
  -
    playerId: 2
    playerName: "Jiten"
    playerCountry: "India"
    playerClub: "Bulls"